# Generated by Django 3.0.5 on 2020-04-27 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('state', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='delevery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('Phone', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('state', models.IntegerField(default=1)),
                ('Price', models.IntegerField(default=15)),
                ('count', models.IntegerField(default=100)),
                ('image', models.FileField(blank=True, null=True, upload_to=' Profile_image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('long_position', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('lat_position', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('delevery', models.CharField(blank=True, max_length=14, null=True)),
                ('delevery_num', models.CharField(blank=True, max_length=14, null=True)),
                ('delevery_date', models.DateField(null=True)),
                ('Phone', models.CharField(max_length=15, null=True)),
                ('Adrress', models.CharField(max_length=200, null=True)),
                ('state_pay', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Get',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
    ]
